llm:
  provider: ollama
  config:
    model: 'wizardlm2:7b'
    temperature: 0.5
    max_tokens: 500
    top_p: 1
    base_url: 'http://localhost:11434'
embedder:
  provider: ollama
  config:
    model: 'znbang/bge:small-en-v1.5-q8_0'